export default {
    SIGNUP: 'SIGNUP',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNIN: 'SIGNIN',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNOUT: 'SIGNOUT',
    ADD_INVITE: 'ADD_INVITE',
    ADD_INVITE_SUCCESS: 'ADD_INVITE_SUCCESS',
    GET_INVITES: 'GET_INVITES',
    GET_INVITES_SUCCESS: 'GET_INVITES_SUCCESS',   
}